spring.application.name=helma_backend
spring.datasource.url=jdbc:mysql://localhost:3306/helma_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
server.port=8082
server.servlet.context-path=/f
groq.api.key=
app.security.disabled=false