export enum Sector {
  TECHNOLOGY = 'TECHNOLOGY',
  FINTECH_FINANCIAL_SERVICES = 'FINTECH_FINANCIAL_SERVICES',
  HEALTH_BIO = 'HEALTH_BIO',
  CONSUMER_PRODUCTS = 'CONSUMER_PRODUCTS',
  COMMERCE_MARKETPLACES = 'COMMERCE_MARKETPLACES',
  CLIMATE_ENERGY = 'CLIMATE_ENERGY',
  REAL_ESTATE_BUILT_ENVIRONMENT = 'REAL_ESTATE_BUILT_ENVIRONMENT',
  MOBILITY_INDUSTRY_LOGISTICS = 'MOBILITY_INDUSTRY_LOGISTICS',
  EDUCATION_WORK = 'EDUCATION_WORK',
  MEDIA_COMMUNITY_LEISURE = 'MEDIA_COMMUNITY_LEISURE'
}

export enum SubSector {
  AI = 'AI',
  SAAS = 'SAAS',
  CYBERSECURITY = 'CYBERSECURITY',
  DATA_ANALYTICS = 'DATA_ANALYTICS',
  PAYMENTS = 'PAYMENTS',
  EMBEDDED_FINANCE = 'EMBEDDED_FINANCE',
  ACCOUNTING_FINANCE_SOFTWARE = 'ACCOUNTING_FINANCE_SOFTWARE',
  DIGITAL_HEALTH = 'DIGITAL_HEALTH',
  WELLNESS = 'WELLNESS',
  MENTAL_HEALTH = 'MENTAL_HEALTH',
  FOOD_BEVERAGE = 'FOOD_BEVERAGE',
  FASHION_APPAREL = 'FASHION_APPAREL',
  BEAUTY_PERSONAL_CARE = 'BEAUTY_PERSONAL_CARE',
  D2C_BRANDS = 'D2C_BRANDS',
  ONLINE_MARKETPLACE = 'ONLINE_MARKETPLACE',
  ECOMMERCE_ENABLEMENT = 'ECOMMERCE_ENABLEMENT',
  CLEAN_ENERGY = 'CLEAN_ENERGY',
  CLIMATE_SOFTWARE = 'CLIMATE_SOFTWARE',
  SUSTAINABLE_MATERIALS = 'SUSTAINABLE_MATERIALS',
  PROPTECH = 'PROPTECH',
  LOGISTICSTECH = 'LOGISTICSTECH',
  INDUSTRIAL_AUTOMATION = 'INDUSTRIAL_AUTOMATION',
  FUTURE_OF_WORK = 'FUTURE_OF_WORK',
  PRODUCTIVITY_TOOLS = 'PRODUCTIVITY_TOOLS',
  GAMING = 'GAMING',
  CREATOR_ECONOMY = 'CREATOR_ECONOMY'
}

export enum AppTag {
  B2B = 'B2B',
  B2C = 'B2C',
  MARKETPLACE = 'MARKETPLACE',
  SUBSCRIPTION = 'SUBSCRIPTION',
  HARDWARE = 'HARDWARE',
  SOFTWARE = 'SOFTWARE',
  MOBILE_APP = 'MOBILE_APP',
  D2C = 'D2C',
  RECURRING_REVENUE = 'RECURRING_REVENUE',
  DEEPTECH = 'DEEPTECH',
  IMPACT = 'IMPACT',
  SUSTAINABLE = 'SUSTAINABLE',
  LOCAL = 'LOCAL',
  GLOBAL = 'GLOBAL',
  SMB = 'SMB',
  ENTERPRISE = 'ENTERPRISE',
  CONSUMER_BRAND = 'CONSUMER_BRAND',
  REGULATED = 'REGULATED',
  DATA_DRIVEN = 'DATA_DRIVEN',
  AUTOMATION = 'AUTOMATION'
}

export const SECTOR_OPTIONS = Object.values(Sector);

export const TAG_OPTIONS = Object.values(AppTag);

export const SUB_SECTOR_OPTIONS_BY_SECTOR: Record<Sector, readonly SubSector[]> = {
  [Sector.TECHNOLOGY]: [
    SubSector.AI,
    SubSector.SAAS,
    SubSector.CYBERSECURITY,
    SubSector.DATA_ANALYTICS
  ],
  [Sector.FINTECH_FINANCIAL_SERVICES]: [
    SubSector.PAYMENTS,
    SubSector.EMBEDDED_FINANCE,
    SubSector.ACCOUNTING_FINANCE_SOFTWARE
  ],
  [Sector.HEALTH_BIO]: [
    SubSector.DIGITAL_HEALTH,
    SubSector.WELLNESS,
    SubSector.MENTAL_HEALTH
  ],
  [Sector.CONSUMER_PRODUCTS]: [
    SubSector.FOOD_BEVERAGE,
    SubSector.FASHION_APPAREL,
    SubSector.BEAUTY_PERSONAL_CARE
  ],
  [Sector.COMMERCE_MARKETPLACES]: [
    SubSector.D2C_BRANDS,
    SubSector.ONLINE_MARKETPLACE,
    SubSector.ECOMMERCE_ENABLEMENT
  ],
  [Sector.CLIMATE_ENERGY]: [
    SubSector.CLEAN_ENERGY,
    SubSector.CLIMATE_SOFTWARE,
    SubSector.SUSTAINABLE_MATERIALS
  ],
  [Sector.REAL_ESTATE_BUILT_ENVIRONMENT]: [SubSector.PROPTECH],
  [Sector.MOBILITY_INDUSTRY_LOGISTICS]: [
    SubSector.LOGISTICSTECH,
    SubSector.INDUSTRIAL_AUTOMATION
  ],
  [Sector.EDUCATION_WORK]: [
    SubSector.FUTURE_OF_WORK,
    SubSector.PRODUCTIVITY_TOOLS
  ],
  [Sector.MEDIA_COMMUNITY_LEISURE]: [
    SubSector.GAMING,
    SubSector.CREATOR_ECONOMY
  ]
};
