package com.helma.helmabackend.entity.crowdfunding.enums;

public enum Sector {
    TECHNOLOGY,
    FINTECH_FINANCIAL_SERVICES,
    HEALTH_BIO,
    CONSUMER_PRODUCTS,
    COMMERCE_MARKETPLACES,
    CLIMATE_ENERGY,
    REAL_ESTATE_BUILT_ENVIRONMENT,
    MOBILITY_INDUSTRY_LOGISTICS,
    EDUCATION_WORK,
    MEDIA_COMMUNITY_LEISURE
}