package com.helma.helmabackend.entity.crowdfunding.enums;

public enum SubSector {
    AI,
    SAAS,
    CYBERSECURITY,
    DATA_ANALYTICS,

    PAYMENTS,
    EMBEDDED_FINANCE,
    ACCOUNTING_FINANCE_SOFTWARE,

    DIGITAL_HEALTH,
    WELLNESS,
    MENTAL_HEALTH,

    FOOD_BEVERAGE,
    FASHION_APPAREL,
    BEAUTY_PERSONAL_CARE,

    D2C_BRANDS,
    ONLINE_MARKETPLACE,
    ECOMMERCE_ENABLEMENT,

    CLEAN_ENERGY,
    CLIMATE_SOFTWARE,
    SUSTAINABLE_MATERIALS,

    PROPTECH,

    LOGISTICSTECH,
    INDUSTRIAL_AUTOMATION,

    FUTURE_OF_WORK,
    PRODUCTIVITY_TOOLS,

    GAMING,
    CREATOR_ECONOMY
}